# disk_config/iso-kde.toml

image = "ghcr.io/guy-amun-ra/kyanite-image-template:latest"

[customizations.installer.kickstart]
contents = """
%post
bootc switch --mutate-in-place --transport registry ghcr.io/ublue-os/image-template:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]

disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]

# Custom kernel parameters for GPD Pocket 4 tweaks, including screen rotation
[customizations.kernel]
kernel_cmdline = "quiet splash fbcon=rotate:1 video=eDP-1:panel_orientation=right_side_up"

# Optional: Additional customizations, like setting locale, hostname etc.
[customizations.image]
hostname = "kyanite"

# You can add other container image specific labels or settings here as supported
