Section "Device"
    Identifier "Inteldrt"
    Driver "intel"
    Option "TearFree" "true"
    Option "AccelMethod" "sna"
EndSection

Section "Monitor"
    Identifier "eDP-1"
    Option "Rotate" "right"
EndSection

Section "InputClass"
    Identifier "touchscreen"
    MatchIsTouchpad "on"
    Option "Calibration" "0 1920 0 1080"
    Option "InvertY" "true"
EndSection
